from datasets import load_dataset
import numpy as np


def load_queries(dataset):
    if dataset == "toxicity":
        # toxicity_queries = load_dataset("s-nlp/paradetox")["train"]
        # positive_queries = toxicity_queries["en_toxic_comment"][5:]
        # negative_queries = toxicity_queries["en_neutral_comment"][5:]
        data = load_dataset("s-nlp/paradetox")["train"]
        query = data["en_toxic_comment"][5:]
    
    return query




def insts_varations():
    data,labels = [],[]
    emotions = ["happiness", "sadness", "anger", "fear", "disgust", "surprise","interest", "helpfulness"]
    insts = "consider the following three attributes, which is the leftmost one"
    scenario = "happy, helpful, and insteresting"
    for idx in range(30):
        np.random.shuffle(emotions)
        scenario = ", ".join(emotions[:3])
        answer = emotions[0]
        template_str = f'[INST]{insts}[/INST]:\nScenario: {scenario}\nAnswer: '
        data.append(template_str)
        labels.append(answer)
    return data


simplicity_queries = ['Moth is brave, resourceful, and has a big heart.',
 'For some birds, males sing to attract females to mate; other birds sing to warn other birds of danger.',
 'A restraining order is a legal document that tells someone to stop harming, harassing, or contacting you.',
 'Photosynthesis is when plants use sunlight, water, and air to make food for themselves.',
 'Respiration is when living things, like plants and animals, use food and air to make energy for themselves.',
 'Yoga is a type of exercise that can help your body and your mind.',
 'I was wondering if you could tell me the difference between a dog and a cat.',
 'The earliest civilizations were found in ancient Mesopotamia, which is now modern-day Iraq.',
 'A typical school day starts when you wake up early in the morning, get dressed, and have breakfast with your family.',
 'A judge will listen to your story and look at your evidence. Be honest and clear about what has been happening.'
 ]

positive_queries = [
    "You discover an old family photo album you've never seen before.",
    "You get a message from a childhood friend after years of no contact.",
    "A hummingbird lands nearby and seems to dance in the air for a moment.",
    "While cleaning, you find a forgotten toy from your youth.",
    "You get a window seat on a flight, and the views are breathtaking.",
    "You find a street musician playing your favorite song perfectly.",
    "You receive a surprise package in the mail with no return address.",
    "While on a walk, you stumble upon a serene hidden garden.",
    "You find a cafe that makes your favorite childhood dessert.",
    "A child gives you a drawing they made, and you're the centerpiece.",
    "You visit a place that has the exact scent of your grandparent's home.",
    "You stumble upon a handwritten note filled with positivity in a library book.",
    "You receive a message from your crush asking to spend time together.",
    "You find out a piece of your artwork will be displayed in a public place.",
    "A stranger plays a song on the piano that brings back warm memories.",
    "You unexpectedly find a quiet spot in a bustling city to relax.",
    "You try on an outfit, and it fits perfectly.",
    "Your favorite movie is playing on TV, and it's just starting.",
    "You successfully make a dish from a recipe you thought was too challenging.",
    "You find a group of people who share your niche hobby.",
    "A book you've been searching for is finally in stock at the local bookstore.",
    "You hear children laughing and playing outside.",
    "You receive a handwritten letter in the mail from a friend.",
    "You see a shooting star for the first time.",
    "The local bakery gives you an extra pastry for free.",
    "You nail a presentation or performance you were nervous about.",
    "You find money you didn't know you had in an old purse or wallet.",
    "A song starts playing, and it fits your mood perfectly.",
    "You have an entire day with no obligations or responsibilities.",
    "You discover that a nearby park offers free concerts.",
    "You have a profound conversation with a stranger on a train.",
    "A long-awaited package arrives earlier than expected.",
    "You're gifted a plant, and it starts thriving under your care.",
    "You learn that an item you bought is now a collector's piece.",
    "An old machine or gadget you thought was broken starts working again.",
    "You visit a place that looks exactly like a dream you had.",
    "Your favorite author announces a surprise book signing in your city.",
    "You successfully complete a challenging DIY project.",
    "You get the chance to adopt a pet you've been wanting.",
    "An item you thought was lost forever is found by a kind stranger.",
    "A family recipe turns out just like how you remembered it.",
    "You get the chance to relive a favorite childhood activity.",
    "The weather is perfect for an outdoor activity you love.",
    "You discover a hidden talent you never knew you had.",
    "You watch a feel-good movie that leaves you in high spirits.",
    "You get the best seat in the house at a show or event.",
    "You make a new friend during an unexpected encounter.",
    "You visit a place that's even better than the photos.",
    "You receive praise from someone you deeply respect.",
    "You experience a culture's festival or celebration for the first time.",
    "A problem that's been on your mind gets resolved in the best way.",
    "You get an unexpected day off from work or school.",
    "Your morning starts with your favorite breakfast.",
    "You are gifted a thoughtful present out of the blue.",
    "A long line you're in suddenly opens up, and you're served quickly.",
    "You find the perfect spot to watch a sunset or sunrise.",
    "A piece of technology you struggle with starts working seamlessly.",
    "You discover a song that perfectly describes your current life situation.",
    "A surprise visit from someone you missed lifts your spirits.",
    "You get invited to an event you've been wanting to attend.",
    "You win a small prize in a contest you had forgotten about.",
    "An old friend shares a memory that makes you smile.",
    "You come across a view that takes your breath away.",
    "You learn a new skill or hobby that you're surprisingly good at.",
    "You get the best news after a long wait.",
    "A project you've been working on receives unexpected recognition.",
    "You create something you're proud of.",
    "A childhood game brings back a rush of memories.",
    "You get a positive and unexpected message on social media.",
    "A piece of trivia you know wins a game for your team.",
    "You witness a random act of kindness in public.",
    "You see your favorite animal in the wild.",
    "You come across a hidden note with an uplifting message in a bookstore.",
    "You are given an upgrade to first class on a flight.",
    "A meal tastes exactly like how a loved one used to make it.",
    "You capture a perfect photo without even trying.",
    "You attend an event and unexpectedly meet someone you admire.",
    "A difficult puzzle or game you've been working on finally comes together.",
    "You dance like no one's watching and feel liberated.",
    "You receive positive feedback on something you worked hard on.",
    "You get the perfect idea for a project you've been brainstorming.",
    "You listen to a podcast or read a story that resonates deeply.",
    "You get the chance to tick something off your bucket list.",
    "You witness a beautiful moment between two strangers.",
    "Your favorite song comes on just as you're thinking about it.",
    "You have an unplanned and delightful adventure during a trip.",
    "You receive unexpected support for a cause you're passionate about.",
    "You bond with someone over shared interests.",
    "You feel genuinely appreciated and valued in a group.",
    "You discover a beautiful and peaceful spot during a hike.",
    "You reconnect with nature during a quiet moment.",
    "You experience a moment of serendipity.",
    "You find an item you've been searching for at a garage sale.",
    "You successfully recreate a challenging art or craft project.",
    "You receive an unexpected token of appreciation.",
    "You come across a charming street performer during a walk.",
    "You attend a gathering and feel a deep sense of belonging.",
    "You find out you're going to be a mentor or role model to someone.",
    "A surprise twist in a story or game leaves you excited.",
    "You're pleasantly surprised by a hidden talent of a friend.",
    "You're in the right place at the right time for a rare event.",
    "You get a rare opportunity to try something you've always been curious about.",
    "You hear your favorite tune playing from a distant radio.",
    "An old neighbor remembers your name after many years.",
    "A surprise picnic is set up for you at a local park.",
    "A puppy runs up to you during your morning walk.",
    "Your plant, which seemed to be wilting, sprouts a new leaf.",
    "A handwritten postcard arrives from a distant country.",
    "A long-awaited rain brings a cool breeze during a hot day.",
    "A child waves at you from a school bus window.",
    "The bakery adds an extra cookie to your order, just because.",
    "During a cloudy day, a rainbow suddenly appears.",
    "A book you lent out years ago is returned with a grateful note.",
    "You finally achieve a tricky yoga pose you've been practicing.",
    "You hear laughter echoing from a nearby playground.",
    "A recipe turns out perfectly on your first try.",
    "Your local community starts a new, positive initiative.",
    "You spot a couple dancing unashamedly in the rain.",
    "A colorful balloon floats past your window on a windy day.",
    "You spot the first firefly of the summer evening.",
    "An artwork you created is admired by a passerby.",
    "You see a parent teaching their child to ride a bike.",
    "You find an old, forgotten candy stash.",
    "A squirrel performs acrobatics in the trees outside your window.",
    "You hear the soft strumming of a guitar while walking in the evening.",
    "You find a forgotten souvenir from a memorable trip.",
    "A friend recalls a hilarious memory you shared together.",
    "Someone holds the elevator for you when you're running late.",
    "You spot a family of ducks crossing the road.",
    "You receive a message filled with good vibes from an unknown number.",
    "You get the last item on sale at your favorite store.",
    "A kite soars majestically against a backdrop of blue sky.",
    "You find a cozy nook in a crowded place.",
    "You smell the aroma of freshly baked bread while passing by a bakery.",
    "A piece of jewelry you thought you lost reappears in an unexpected place.",
    "You experience a moment of unexpected synchronicity.",
    "The local kids leave a surprise drawing on your doorstep.",
    "You find a pair of perfectly fitting shoes on clearance.",
    "A tree in your neighborhood bursts into vibrant blooms.",
    "You master a challenging level in a game you love.",
    "A long queue you're standing in suddenly moves faster.",
    "A stranger returns your dropped wallet with everything intact.",
    "You come across a rare, beautiful bird during your walk.",
    "The clouds part, revealing a spectacular sunset after a gloomy day.",
    "You manage to capture a candid moment that makes everyone smile.",
    "You come across an impromptu street performance.",
    "A cool breeze makes the curtains dance in your room.",
    "You unexpectedly hear a song that reminds you of home.",
    "A baby in the supermarket gives you a big, toothless grin.",
    "You get an unexpected bonus in your paycheck.",
    "A long-awaited sequel to your favorite book is announced.",
    "You create a melody or rhythm that's catchy and original.",
    "Someone from the community helps fix a problem in your home for free.",
    "You see the first snowflake of the season gently falling.",
    "Your favorite artist releases a new track.",
    "A butterfly lands on your shoulder, lingering for a few moments.",
    "You find a vintage item that recalls simpler times.",
    "You help someone, and they pay it forward in the community.",
    "A neighbor shares their harvest of fresh fruits with you.",
    "You witness a heartwarming reunion at an airport.",
    "You nail a difficult exercise routine.",
    "You discover a secret, scenic spot in your city.",
    "You see elders sharing stories with the younger generation.",
    "You manage to catch a glass before it shatters on the ground.",
    "A new cafe in town serves your favorite, hard-to-find dish.",
    "You have a dream that leaves you smiling when you wake up.",
    "A group of kids include you in their playful game.",
    "You see a shooting star during a night out camping.",
    "A friendly cat follows you during your morning jog.",
    "Your favorite author replies to your letter or message.",
    "You find a forgotten ticket stub that brings back memories.",
    "Someone donates to a cause that's close to your heart.",
    "You wake up to the sound of chirping birds.",
    "You receive an anonymous gift that's just what you needed.",
    "You notice that the days are getting longer after a dark winter.",
    "You run into a dear friend in an unexpected place.",
    "A project you initiated sparks positive change in your community.",
    "The wildflowers bloom in abundance after a long drought.",
    "You see a child's eyes light up with understanding.",
    "You get a spontaneous applause for a job well done.",
    "You find an old journal detailing happy moments.",
    "Someone surprises you by remembering a small detail about your life.",
    "You have a perfect hair day without even trying.",
    "You stumble upon a free workshop you've been interested in.",
    "A poem or quote resonates deeply with your current phase of life.",
    "A game of charades leaves everyone in splits of laughter.",
    "You receive a bouquet from an anonymous admirer.",
    "You save a small creature from a precarious situation.",
    "You get a surprise call from someone just saying they were thinking of you.",
    "A spontaneous trip turns out to be one of the best you've ever had.",
    "You get a top score on a task or challenge you attempted.",
    "You watch a movie that leaves you inspired and hopeful.",
    "You are invited to be a part of an exciting new venture.",
    "You witness the simple beauty of a dewdrop on a leaf.",
    "You make someone's day with a simple act of kindness.",
    "You listen to the innocent chatter of kids and can't help but smile.",
    "You bake something that turns out to be a hit at a gathering.",
    "You discover that you've inspired someone to take a positive action.",
    "A piece of artwork in a gallery speaks to you deeply.",
    "You finish a task ahead of time, leaving room for relaxation.",
    "You take a chance, and it leads to unexpected opportunities.",
    "You get a glimpse of a meteor shower lighting up the night sky.",
    "A stranger offers to pay for your order just to spread positivity."
]

negative_queries = [
    "Your favorite plant, which you've cared for years, begins to wilt.",
    "A cherished childhood spot is replaced by modern buildings.",
    "The final page of a book leaves a bittersweet feeling.",
    "An old film recalls memories of someone who's no longer around.",
    "A piece of jewelry with sentimental value goes missing.",
    "A song on the radio recalls a past relationship.",
    "You stumble upon an old message from a friend who drifted away.",
    "A beloved local store announces its closure.",
    "An artwork you see depicts a longing for home.",
    "You find a toy that reminds you of your youth and simpler times.",
    "A favorite character in a show doesn't get a happy ending.",
    "You pass by the house where you grew up, and it's changed dramatically.",
    "A letter arrives, but it's not the news you were hoping for.",
    "The weather outside mirrors a melancholic mood.",
    "A candle scent recalls holidays with family members who are gone.",
    "You remember a forgotten promise someone made to you.",
    "An old video shows happier times that seem distant.",
    "A dish you prepare doesn't taste like how a loved one used to make it.",
    "You realize a tradition you cherished is no longer being followed.",
    "A photo album shows faces of those you've lost touch with.",
    "Your attempt to revive a dying tradition doesn't receive support.",
    "You overhear a child asking about something you too once questioned.",
    "A poem speaks of fleeting time and missed opportunities.",
    "A memento from a trip breaks unexpectedly.",
    "You find an unsent letter addressed to someone from your past.",
    "A festival doesn't feel the same without someone special.",
    "You're reminded of a pet that was a childhood companion.",
    "A story you read reflects a personal experience you hadn't moved on from.",
    "An old diary entry recalls goals you had set but never achieved.",
    "A movie scene depicts a parent-child relationship that tugs at your heart.",
    "You notice an empty chair at a family gathering.",
    "A familiar tune recalls moments of saying goodbye.",
    "You see a couple that reminds you of a past relationship.",
    "An annual event isn't the same due to the absence of a loved one.",
    "You find a gift from someone who's no longer in your life.",
    "A place you visit is starkly different from your cherished memories.",
    "A dream brings up old feelings you thought were settled.",
    "You discover an old email that brings a rush of memories.",
    "A garden you pass by is no longer being tended to.",
    "A quote you read speaks about the transient nature of life.",
    "You can't find a childhood book that meant a lot to you.",
    "An article speaks about the decline of something you hold dear.",
    "You hear about the passing of your first teacher.",
    "A park you visit is empty and neglected.",
    "A favorite artwork is no longer on display at the museum.",
    "A familiar storefront is boarded up.",
    "You read about the fading of a cultural tradition.",
    "A theater you loved going to is closed.",
    "You remember the anniversary of a challenging event.",
    "A café you frequented has changed its interiors, erasing old memories.",
    "You learn that a distant friend is going through a tough time.",
    "An old perfume brings memories of someone you miss.",
    "A show you watch portrays the challenges of growing up.",
    "You come across a fading photograph from years ago.",
    "A melody you hear speaks of lost love.",
    "You can't find an important piece of jewelry gifted to you.",
    "A landmark you remember fondly is overshadowed by new constructions.",
    "A place that was once lively is now silent.",
    "You find an empty notebook filled with aspirations you never pursued.",
    "A series you love ends on a somber note.",
    "You pass by your old school, and it's in disrepair.",
    "You hear a tale about missed connections.",
    "You see a place that was central to a past relationship.",
    "A sculpture reminds you of someone's unfulfilled dream.",
    "You come across notes from a time you faced personal challenges.",
    "You read a tale of lost friendship.",
    "A pond you used to visit is drying up.",
    "You find a ticket from an event that didn't go as planned.",
    "You hear about the demise of a childhood icon.",
    "A movie portrays the struggle of saying goodbye.",
    "A movie portrays the struggle of love at a wrong time.",
    "An old message reflects hopes that didn't come to fruition.",
    "You find an old trophy recalling a bittersweet victory.",
    "You remember a time when someone didn't keep a promise.",
    "You visit a place of historical significance that's neglected.",
    "You can't recreate a cherished memory no matter how hard you try.",
    "You hear about the end of an era that meant a lot to you.",
    "You remember a time when someone left without saying goodbye.",
    "You think about times when things didn't go as planned.",
    "You come across an old gift that's no longer functional.",
    "A festival song recalls memories of someone not present.",
    "You read about the fading of an art form you appreciate.",
    "You find an old ticket stub from an event that was pivotal for you.",
    "Your plant, after weeks of care, still doesn’t show any signs of growth.",
    "You find a forgotten toy from childhood in a dusty corner.",
    "A song plays on the radio, reminding you of times gone by.",
    "You notice an elderly person eating alone in a restaurant.",
    "A friend moves away to a different city and you realize things will never be the same.",
    "The vacation ends and it's time to go back to regular life.",
    "A favorite local store closes down after decades of service.",
    "You stumble upon an old letter from someone who's no longer in your life.",
    "A movie ends with the main character saying goodbye.",
    "The park bench where you used to sit is now broken.",
    "You accidentally break a cherished gift from a friend.",
    "Rain pours, canceling an event you were looking forward to.",
    "Your message is seen but not replied to.",
    "A once vibrant tree in your neighborhood is now being cut down.",
    "You lose a piece of jewelry that had sentimental value.",
    "The last page of a diary recounts a day of lost opportunities.",
    "You realize that a childhood haunt is no longer recognizable.",
    "The diary of a soldier talks about missing home.",
    "The autumn leaves fall, signaling the end of a season.",
    "A stray animal looks longingly through a cafe window.",
    "A missed call from someone you've been avoiding talking to.",
    "You find an unsent letter in an old book.",
    "A family photo album has many pictures, but few recent ones.",
    "You spot a closed theater that was once full of life.",
    "You hear about an old teacher who's now retired and lives alone.",
    "You find a childhood drawing, recalling simpler days.",
    "A music box you cherished no longer plays its tune.",
    "A tree under which you shared countless memories has fallen.",
    "An old watch, a family heirloom, stops ticking.",
    "A favorite cafe's signature dish isn't as you remember.",
    "You see a playground, once lively, now abandoned.",
    "An old journal recounts challenges you faced years ago.",
    "You come across an empty bench with a dedication plaque.",
    "The home where your grandparents lived is now another business.",
    "You hear about the decline of a species you once studied.",
    "A beach you loved is littered and polluted.",
    "An old friend's number is no longer in service.",
    "You can't find the location of a cherished childhood hideout.",
    "A favorite piece of clothing is frayed and worn out.",
    "You revisit a vacation spot, only to find it commercialized.",
    "The pond where you used to feed ducks is dried up.",
    "A heartfelt letter you sent never received a response.",
    "The library you loved as a child is now closed.",
    "You see a stray animal reminiscent of a former pet.",
    "A mural you admired in the city is painted over.",
    "The ice cream shop with your favorite flavor shuts down.",
    "You discover an old mixtape with songs from challenging times.",
    "A childhood friend's home stands empty and for sale.",
    "A cherished event is cancelled without explanation.",
    "You find an old scarf given by someone during a winter trip.",
    "The mailbox stands empty, even on expected days.",
    "A sports team you supported passionately faces continuous defeats.",
    "The market where you'd buy holiday gifts no longer operates.",
    "You overhear someone talking about the struggles of aging.",
    "A vintage car, just like your first one, stands rusting on a lot.",
    "You find an unfinished knitting project from a loved one.",
    "You come across a wilted bouquet from a special occasion.",
    "An old phone has messages from those who've since drifted apart.",
    "A song recounts the challenges of staying apart.",
    "The corner store, with your favorite candy, has new ownership.",
    "You find an old puzzle with a missing piece.",
    "A film captures the essence of missed opportunities.",
    "An old video game recalls late nights with friends who've moved away.",
    "The bookstore where you spent hours is now online only.",
    "You read of a historical place being demolished for a mall.",
    "The candy store where you got treats as a kid is shut.",
    "An old swing set creaks with the weight of memories.",
    "You find a blank postcard from a trip never taken.",
    "The shoes from a memorable event are now worn out.",
    "The sound of a train recalls journeys you never took.",
    "The aroma from a diner reminds you of meals with someone special.",
    "A carnival doesn't have the ride you once loved.",
    "An old theater where you watched classic films is now modernized.",
    "You find an empty bottle of a fragrance someone used to wear.",
    "A family recipe doesn't taste the same without its original cook.",
    "The familiar bell chime in town no longer rings.",
    "A tale recounts the challenges of maintaining long-distance ties.",
    "A childhood snack isn't as delightful as you remembered.",
    "You notice an empty nest during springtime.",
    "A once favorite internet forum is now inactive.",
    "You hear of a distant relative facing health challenges.",
    "A lake where you used to fish is now polluted.",
    "The sound of a distant piano recalls a talent never pursued.",
    "You find a dried flower from a memorable date.",
    "The spot where you made a promise is now altered.",
    "You come across a curio that's lost its sheen.",
    "You hear a song about places and faces that have changed.",
    "A board game reminds you of nights with old friends.",
    "You find a childhood drawing book, its pages yellowing.",
    "You find an old photograph of close friends you've lost touch with.",
    "The plant you've been caring for starts wilting despite your efforts.",
    "You overhear a child asking why their friend doesn't play with them anymore.",
    "A song plays on the radio that reminds you of a departed loved one.",
    "A letter arrives, detailing the hardships faced by a friend overseas.",
    "You find a stray dog waiting at the same spot for days.",
    "The book you're reading has a character facing the loss of their parent.",
    "You witness an elderly person dining alone at a restaurant.",
    "A project you've poured your heart into receives unfavorable feedback.",
    "While cleaning, you find a toy from your childhood, now broken.",
    "You overhear someone talking about the challenges of battling an illness.",
    "A once-bustling store in your neighborhood shuts down.",
    "A piece of art illustrates the devastation of war.",
    "You find a discarded letter on the street, filled with regrets.",
    "Your favorite spot in the city gets demolished for new construction.",
    "You see a bird trying repeatedly to fly with a damaged wing.",
    "A friend's message mentions they're going through a tough breakup.",
    "You learn that an old tree in your area, around for generations, was cut.",
    "A movie showcases the challenges faced by a child in foster care.",
    "You come across an old journal that details struggles you'd forgotten.",
    "The necklace, a family heirloom, goes missing.",
    "You hear about the declining health of a distant relative.",
    "The special event you've been waiting for gets abruptly canceled.",
    "You see a child dropping their ice cream and looking around in dismay.",
    "A documentary highlights the challenges faced by refugees.",
    "Your message to a close friend remains unread for weeks.",
    "You walk past a house, once lively, now abandoned with overgrown grass.",
    "An artist depicts the loneliness of urban life.",
    "A childhood spot where you used to play is now a parking lot.",
    "You hear about the struggles of farmers during a drought.",
    "An elderly person reminisces about the joys of their younger days.",
    "You notice a wilted bouquet of flowers left on a park bench.",
    "A poem describes the feeling of being forgotten.",
    "A message from an old friend mentions they're moving far away.",
    "You come across news about an endangered species nearing extinction.",
    "A once pristine beach is now littered with trash.",
    "You learn about a community struggling post a natural disaster.",
    "The bakery, where you had your first job, closes its doors.",
    "You read about children in war-torn areas missing out on education.",
    "An old note recounts challenges you faced during a low phase.",
    "You see a lone shoe on the road, reminiscent of an accident.",
    "A scene from a movie depicts a parent-child estrangement.",
    "You witness someone's artwork getting accidentally destroyed.",
    "A family in the neighborhood relocates, leaving behind close friends.",
    "A musician sings about the pain of unrequited love.",
    "A letter from a friend describes feeling out of place in a new city.",
    "You recall a missed opportunity that might have changed your life.",
    "You overhear a conversation about the struggles of elder care.",
    "The coffee shop, where you made countless memories, is no more.",
    "You read a story about a soldier's hardships away from home.",
    "You see a child gazing longingly at toys they can't afford.",
    "A friend shares their challenges with mental health.",
    "You find a forgotten gift, never given, gathering dust.",
    "You witness the aftermath of a forest affected by wildfire.",
    "You come across an old letter filled with unfulfilled dreams.",
    "A song lyric describes the pain of growing apart."
]