#!/bin/bash

python train_dpo.py \
--model_name_or_path  "/scratch/prj/lmrep/llama2_model/Llama-2-7b-chat-hf" \
--dataset_name 'hh_rlhf_helpful_paired_data' \
--eval_dataset 'hh_rlhf_helpful_paired_data' \
--reward_types 'alignment' \
--use_label 'False' \
--user_tag '[INST]' \
--assistant_tag '#Response:' \
--pos_type 'a non-toxic' \
--neg_type 'an aggressive' \
--control_template "Give {type} answer." \
--target_layers "10,12,14,16,18,20" \
--do_eval \
--lorra_alpha 5 \
--lorra_beta 0 \
--lora_r 8 \
--lora_alpha 16 \
--lora_dropout 0.05 \
--output_dir ./results/single_dpo/hh_helpful \
--overwrite_output_dir \
--num_train_epochs 50 \
--bf16 True \
--evaluate_nums 200 \
--per_device_train_batch_size 8 \
--per_device_eval_batch_size 16 \
--gradient_accumulation_steps 1 \
--evaluation_strategy "steps" \
--eval_steps 50  \
--save_strategy "steps" \
--save_steps 150 \
--learning_rate 3e-4 \
--weight_decay 0. \
--lr_scheduler_type "constant" \
--logging_strategy "steps" \
--logging_steps 50 \
--tf32 True \
--model_max_length 128 \
--q_lora False \
--gradient_checkpointing True \
--report_to "wandb" \