python3 icv_inference.py \
--dataset hh_rlhf \
--model_type llama-2 \
--model_size "7b" \
--start_id 0 \
--end_id 200 \
--prompt_type default \
--reward_types hh_rlhf_helpful \
--generate_woICV True \