#!/bin/bash

python train_sft.py \
--model_name_or_path  "/scratch/prj/lmrep/llama2_model/Llama-2-7b-chat-hf" \
--dataset_name $1 \
--eval_dataset $1 \
--reward_types 'alignment' \
--train_schema $2 \
--act_layers "25,26,27,28,29,30,31" \
--use_label 'False' \
--user_tag '[INST]' \
--assistant_tag '#Response:' \
--pos_type 'a non-toxic' \
--neg_type 'an aggressive' \
--control_template "Give {type} answer." \
--target_layers "10,14,18,20,22,24,26,28,30,32" \
--do_eval \
--lorra_alpha 5 \
--lorra_beta 0 \
--lora_r 8 \
--lora_alpha 16 \
--lora_dropout 0.05 \
--output_dir ./results/single_${2}_customised_trl_actlayers_25-31/$1 \
--overwrite_output_dir \
--num_train_epochs 50 \
--bf16 True \
--evaluate_nums 200 \
--per_device_train_batch_size 16 \
--per_device_eval_batch_size 32 \
--gradient_accumulation_steps 8 \
--evaluation_strategy "steps" \
--eval_steps 50  \
--save_strategy "steps" \
--save_steps 50 \
--learning_rate 3e-4 \
--weight_decay 0. \
--lr_scheduler_type "constant" \
--logging_strategy "steps" \
--logging_steps 50 \
--tf32 True \
--q_lora False \
--gradient_checkpointing True \
--report_to "wandb" \